language: python

sudo: false

python:
  - "3.4"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

branches:
  only:
    - 4.0
env:
  - DJANGO_SETTINGS_MODULE=biostar.settings.travis

install:
    - pip install -q -r conf/requirements_travis.txt

script: python -m biostar4.manage test

